from Bio import Entrez
from Bio import SeqIO
import json

# Class converts the keys from the entrezFetchTranscriptRecord function output into objects which return the values from the output.
class objectify:
    def __init__(self, record):
        for key, value in record.items():
            setattr(self, key, value)


def entrezFetchTranscriptRecord(email: str, accession_ID: str):
    '''
    This function requests a transcript's genbank record using the Entrez library. It uses an NM_ or NC_ accession
    number. The accession number, gene symbol, HGNC ID, DNA_sequence, RNA_sequence, Protein_sequence and Protein
    sequence accession number are extracted from the record and stored in a dictionary called, 'record_dict'.

    :params: email: Can be any user e-mail address.
              E.g.: 'A.N.Other@example.com'

      accession_ID: An NCBI representation of genetic record. Usually starts with NC_, NM_ or NP_.
              E.g.: 'NM_000527.5'

    :output: record_dict: A dictionary containing the transcript accession number, gene symbol, HGNC ID, DNA_sequence,
                          RNA_sequence, Protein_sequence and Protein sequence accession number.

                    E.g.: {
                                "ID": "NM_000527.5",
                                "Gene_symbol": "LDLR",
                                "HGNC_ID": "6547",
                                "DNA_sequence": "GTGCAATCGCGGGAAGCCAGGGTTTCCAGCTAGGACACAGCAGGTCGTGATCCGGGTCGGGACACTGCCTGGCAGAGGCTGCGAGCATGGGGCCCTGGGGCTGGAAATTGCGCTGGACCGTCGCCTTGCTCCTCGCCGCGGCGGGGACTGCAGTGGGCGACAGATGCGAAAGAAACGAGTTCCAGTGCCAAGACGGGAAATGCATCTCCTACAAGTGGGTCTGCGATGGCAGCGCTGAGTGCCAGGATGGCTCTGATGAGTCCCAGGAGACGTGCTTGTCTGTCACCTGCAAATCCGGGGACTTCAGCTGTGGGGGCCGTGTCAACCGCTGCATTCCTCAGTTCTGGAGGTGCGATGGCCAAGTGGACTGCGACAACGGCTCAGACGAGCAAGGCTGTCCCCCCAAGACGTGCTCCCAGGACGAGTTTCGCTGCCACGATGGGAAGTGCATCTCTCGGCAGTTCGTCTGTGACTCAGACCGGGACTGCTTGGACGGCTCAGACGAGGCCTCCTGCCCGGTGCTCACCTGTGGTCCCGCCAGCTTCCAGTGCAACAGCTCCACCTGCATCCCCCAGCTGTGGGCCTGCGACAACGACCCCGACTGCGAAGATGGCTCGGATGAGTGGCCGCAGCGCTGTAGGGGTCTTTACGTGTTCCAAGGGGACAGTAGCCCCTGCTCGGCCTTCGAGTTCCACTGCCTAAGTGGCGAGTGCATCCACTCCAGCTGGCGCTGTGATGGTGGCCCCGACTGCAAGGACAAATCTGACGAGGAAAACTGCGCTGTGGCCACCTGTCGCCCTGACGAATTCCAGTGCTCTGATGGAAACTGCATCCATGGCAGCCGGCAGTGTGACCGGGAATATGACTGCAAGGACATGAGCGATGAAGTTGGCTGCGTTAATGTGACACTCTGCGAGGGACCCAACAAGTTCAAGTGTCACAGCGGCGAATGCATCACCCTGGACAAAGTCTGCAACATGGCTAGAGACTGCCGGGACTGGTCAGATGAACCCATCAAAGAGTGCGGGACCAACGAATGCTTGGACAACAACGGCGGCTGTTCCCACGTCTGCAATGACCTTAAGATCGGCTACGAGTGCCTGTGCCCCGACGGCTTCCAGCTGGTGGCCCAGCGAAGATGCGAAGATATCGATGAGTGTCAGGATCCCGACACCTGCAGCCAGCTCTGCGTGAACCTGGAGGGTGGCTACAAGTGCCAGTGTGAGGAAGGCTTCCAGCTGGACCCCCACACGAAGGCCTGCAAGGCTGTGGGCTCCATCGCCTACCTCTTCTTCACCAACCGGCACGAGGTCAGGAAGATGACGCTGGACCGGAGCGAGTACACCAGCCTCATCCCCAACCTGAGGAACGTGGTCGCTCTGGACACGGAGGTGGCCAGCAATAGAATCTACTGGTCTGACCTGTCCCAGAGAATGATCTGCAGCACCCAGCTTGACAGAGCCCACGGCGTCTCTTCCTATGACACCGTCATCAGCAGAGACATCCAGGCCCCCGACGGGCTGGCTGTGGACTGGATCCACAGCAACATCTACTGGACCGACTCTGTCCTGGGCACTGTCTCTGTTGCGGATACCAAGGGCGTGAAGAGGAAAACGTTATTCAGGGAGAACGGCTCCAAGCCAAGGGCCATCGTGGTGGATCCTGTTCATGGCTTCATGTACTGGACTGACTGGGGAACTCCCGCCAAGATCAAGAAAGGGGGCCTGAATGGTGTGGACATCTACTCGCTGGTGACTGAAAACATTCAGTGGCCCAATGGCATCACCCTAGATCTCCTCAGTGGCCGCCTCTACTGGGTTGACTCCAAACTTCACTCCATCTCAAGCATCGATGTCAACGGGGGCAACCGGAAGACCATCTTGGAGGATGAAAAGAGGCTGGCCCACCCCTTCTCCTTGGCCGTCTTTGAGGACAAAGTATTTTGGACAGATATCATCAACGAAGCCATTTTCAGTGCCAACCGCCTCACAGGTTCCGATGTCAACTTGTTGGCTGAAAACCTACTGTCCCCAGAGGATATGGTTCTCTTCCACAACCTCACCCAGCCAAGAGGAGTGAACTGGTGTGAGAGGACCACCCTGAGCAATGGCGGCTGCCAGTATCTGTGCCTCCCTGCCCCGCAGATCAACCCCCACTCGCCCAAGTTTACCTGCGCCTGCCCGGACGGCATGCTGCTGGCCAGGGACATGAGGAGCTGCCTCACAGAGGCTGAGGCTGCAGTGGCCACCCAGGAGACATCCACCGTCAGGCTAAAGGTCAGCTCCACAGCCGTAAGGACACAGCACACAACCACCCGACCTGTTCCCGACACCTCCCGGCTGCCTGGGGCCACCCCTGGGCTCACCACGGTGGAGATAGTGACAATGTCTCACCAAGCTCTGGGCGACGTTGCTGGCAGAGGAAATGAGAAGAAGCCCAGTAGCGTGAGGGCTCTGTCCATTGTCCTCCCCATCGTGCTCCTCGTCTTCCTTTGCCTGGGGGTCTTCCTTCTATGGAAGAACTGGCGGCTTAAGAACATCAACAGCATCAACTTTGACAACCCCGTCTATCAGAAGACCACAGAGGATGAGGTCCACATTTGCCACAACCAGGACGGCTACAGCTACCCCTCGAGACAGATGGTCAGTCTGGAGGATGACGTGGCGTGAACATCTGCCTGGAGTCCCGTCCCTGCCCAGAACCCTTCCTGAGACCTCGCCGGCCTTGTTTTATTCAAAGACAGAGAAGACCAAAGCATTGCCTGCCAGAGCTTTGTTTTATATATTTATTCATCTGGGAGGCAGAACAGGCTTCGGACAGTGCCCATGCAATGGCTTGGGTTGGGATTTTGGTTTCTTCCTTTCCTCGTGAAGGATAAGAGAAACAGGCCCGGGGGGACCAGGATGACACCTCCATTTCTCTCCAGGAAGTTTTGAGTTTCTCTCCACCGTGACACAATCCTCAAACATGGAAGATGAAAGGGGAGGGGATGTCAGGCCCAGAGAAGCAAGTGGCTTTCAACACACAACAGCAGATGGCACCAACGGGACCCCCTGGCCCTGCCTCATCCACCAATCTCTAAGCCAAACCCCTAAACTCAGGAGTCAACGTGTTTACCTCTTCTATGCAAGCCTTGCTAGACAGCCAGGTTAGCCTTTGCCCTGTCACCCCCGAATCATGACCCACCCAGTGTCTTTCGAGGTGGGTTTGTACCTTCCTTAAGCCAGGAAAGGGATTCATGGCGTCGGAAATGATCTGGCTGAATCCGTGGTGGCACCGAGACCAAACTCATTCACCAAATGATGCCACTTCCCAGAGGCAGAGCCTGAGTCACTGGTCACCCTTAATATTTATTAAGTGCCTGAGACACCCGGTTACCTTGGCCGTGAGGACACGTGGCCTGCACCCAGGTGTGGCTGTCAGGACACCAGCCTGGTGCCCATCCTCCCGACCCCTACCCACTTCCATTCCCGTGGTCTCCTTGCACTTTCTCAGTTCAGAGTTGTACACTGTGTACATTTGGCATTTGTGTTATTATTTTGCACTGTTTTCTGTCGTGTGTGTTGGGATGGGATCCCAGGCCAGGGAAAGCCCGTGTCAATGAATGCCGGGGACAGAGAGGGGCAGGTTGACCGGGACTTCAAAGCCGTGATCGTGAATATCGAGAACTGCCATTGTCGTCTTTATGTCCGCCCACCTAGTGCTTCCACTTCTATGCAAATGCCTCCAAGCCATTCACTTCCCCAATCTTGTCGTTGATGGGTATGTGTTTAAAACATGCACGGTGAGGCCGGGCGCAGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGTGGATCATGAGGTCAGGAGATCGAGACCATCCTGGCTAACACGTGAAACCCCGTCTCTACTAAAAATACAAAAAATTAGCCGGGCGTGGTGGCGGGCACCTGTAGTCCCAGCTACTCGGGAGGCTGAGGCAGGAGAATGGTGTGAACCCGGGAAGCGGAGCTTGCAGTGAGCCGAGATTGCGCCACTGCAGTCCGCAGTCTGGCCTGGGCGACAGAGCGAGACTCCGTCTCAAAAAAAAAAAACAAAAAAAAACCATGCATGGTGCATCAGCAGCCCATGGCCTCTGGCCAGGCATGGCGAGGCTGAGGTGGGAGGATGGTTTGAGCTCAGGCATTTGAGGCTGTCGTGAGCTATGATTATGCCACTGCTTTCCAGCCTGGGCAACATAGTAAGACCCCATCTCTTAAAAAATGAATTTGGCCAGACACAGGTGCCTCACGCCTGTAATCCCAGCACTTTGGGAGGCTGAGCTGGATCACTTGAGTTCAGGAGTTGGAGACCAGGCCTGAGCAACAAAGCGAGATCCCATCTCTACAAAAACCAAAAAGTTAAAAATCAGCTGGGTACGGTGGCACGTGCCTGTGATCCCAGCTACTTGGGAGGCTGAGGCAGGAGGATCGCCTGAGCCCAGGAGGTGGAGGTTGCAGTGAGCCATGATCGAGCCACTGCACTCCAGCCTGGGCAACAGATGAAGACCCTATTTCAGAAATACAACTATAAAAAAATAAATAAATCCTCCAGTCTGGATCGTTTGACGGGACTTCAGGTTCTTTCTGAAATCGCCGTGTTACTGTTGCACTGATGTCCGGAGAGACAGTGACAGCCTCCGTCAGACTCCCGCGTGAAGATGTCACAAGGGATTGGCAATTGTCCCCAGGGACAAAACACTGTGTCCCCCCCAGTGCAGGGAACCGTGATAAGCCTTTCTGGTTTCGGAGCACGTAAATGCGTCCCTGTACAGATAGTGGGGATTTTTTGTTATGTTTGCACTTTGTATATTGGTTGAAACTGTTATCACTTATATATATATATATACACACATATATATAAAATCTATTTATTTTTGCAAACCCTGGTTGCTGTATTTGTTCAGTGACTATTCTCGGGGCCCTGTGTAGGGGGTTATTGCCTCTGAAATGCCTCTTCTTTATGTACAAAGATTATTTGCACGAACTGGACTGTGTGCAACGCTTTTTGGGAGAATGATGTCCCCGTTGTATGTATGAGTGGCTTCTGGGAGATGGGTGTCACTTTTTAAACCACTGTATAGAAGGTTTTTGTAGCCTGAATGTCTTACTGTGATCAATTAAATTTCTTAAATGAACCAA",
                                "RNA_sequence": "GUGCAAUCGCGGGAAGCCAGGGUUUCCAGCUAGGACACAGCAGGUCGUGAUCCGGGUCGGGACACUGCCUGGCAGAGGCUGCGAGCAUGGGGCCCUGGGGCUGGAAAUUGCGCUGGACCGUCGCCUUGCUCCUCGCCGCGGCGGGGACUGCAGUGGGCGACAGAUGCGAAAGAAACGAGUUCCAGUGCCAAGACGGGAAAUGCAUCUCCUACAAGUGGGUCUGCGAUGGCAGCGCUGAGUGCCAGGAUGGCUCUGAUGAGUCCCAGGAGACGUGCUUGUCUGUCACCUGCAAAUCCGGGGACUUCAGCUGUGGGGGCCGUGUCAACCGCUGCAUUCCUCAGUUCUGGAGGUGCGAUGGCCAAGUGGACUGCGACAACGGCUCAGACGAGCAAGGCUGUCCCCCCAAGACGUGCUCCCAGGACGAGUUUCGCUGCCACGAUGGGAAGUGCAUCUCUCGGCAGUUCGUCUGUGACUCAGACCGGGACUGCUUGGACGGCUCAGACGAGGCCUCCUGCCCGGUGCUCACCUGUGGUCCCGCCAGCUUCCAGUGCAACAGCUCCACCUGCAUCCCCCAGCUGUGGGCCUGCGACAACGACCCCGACUGCGAAGAUGGCUCGGAUGAGUGGCCGCAGCGCUGUAGGGGUCUUUACGUGUUCCAAGGGGACAGUAGCCCCUGCUCGGCCUUCGAGUUCCACUGCCUAAGUGGCGAGUGCAUCCACUCCAGCUGGCGCUGUGAUGGUGGCCCCGACUGCAAGGACAAAUCUGACGAGGAAAACUGCGCUGUGGCCACCUGUCGCCCUGACGAAUUCCAGUGCUCUGAUGGAAACUGCAUCCAUGGCAGCCGGCAGUGUGACCGGGAAUAUGACUGCAAGGACAUGAGCGAUGAAGUUGGCUGCGUUAAUGUGACACUCUGCGAGGGACCCAACAAGUUCAAGUGUCACAGCGGCGAAUGCAUCACCCUGGACAAAGUCUGCAACAUGGCUAGAGACUGCCGGGACUGGUCAGAUGAACCCAUCAAAGAGUGCGGGACCAACGAAUGCUUGGACAACAACGGCGGCUGUUCCCACGUCUGCAAUGACCUUAAGAUCGGCUACGAGUGCCUGUGCCCCGACGGCUUCCAGCUGGUGGCCCAGCGAAGAUGCGAAGAUAUCGAUGAGUGUCAGGAUCCCGACACCUGCAGCCAGCUCUGCGUGAACCUGGAGGGUGGCUACAAGUGCCAGUGUGAGGAAGGCUUCCAGCUGGACCCCCACACGAAGGCCUGCAAGGCUGUGGGCUCCAUCGCCUACCUCUUCUUCACCAACCGGCACGAGGUCAGGAAGAUGACGCUGGACCGGAGCGAGUACACCAGCCUCAUCCCCAACCUGAGGAACGUGGUCGCUCUGGACACGGAGGUGGCCAGCAAUAGAAUCUACUGGUCUGACCUGUCCCAGAGAAUGAUCUGCAGCACCCAGCUUGACAGAGCCCACGGCGUCUCUUCCUAUGACACCGUCAUCAGCAGAGACAUCCAGGCCCCCGACGGGCUGGCUGUGGACUGGAUCCACAGCAACAUCUACUGGACCGACUCUGUCCUGGGCACUGUCUCUGUUGCGGAUACCAAGGGCGUGAAGAGGAAAACGUUAUUCAGGGAGAACGGCUCCAAGCCAAGGGCCAUCGUGGUGGAUCCUGUUCAUGGCUUCAUGUACUGGACUGACUGGGGAACUCCCGCCAAGAUCAAGAAAGGGGGCCUGAAUGGUGUGGACAUCUACUCGCUGGUGACUGAAAACAUUCAGUGGCCCAAUGGCAUCACCCUAGAUCUCCUCAGUGGCCGCCUCUACUGGGUUGACUCCAAACUUCACUCCAUCUCAAGCAUCGAUGUCAACGGGGGCAACCGGAAGACCAUCUUGGAGGAUGAAAAGAGGCUGGCCCACCCCUUCUCCUUGGCCGUCUUUGAGGACAAAGUAUUUUGGACAGAUAUCAUCAACGAAGCCAUUUUCAGUGCCAACCGCCUCACAGGUUCCGAUGUCAACUUGUUGGCUGAAAACCUACUGUCCCCAGAGGAUAUGGUUCUCUUCCACAACCUCACCCAGCCAAGAGGAGUGAACUGGUGUGAGAGGACCACCCUGAGCAAUGGCGGCUGCCAGUAUCUGUGCCUCCCUGCCCCGCAGAUCAACCCCCACUCGCCCAAGUUUACCUGCGCCUGCCCGGACGGCAUGCUGCUGGCCAGGGACAUGAGGAGCUGCCUCACAGAGGCUGAGGCUGCAGUGGCCACCCAGGAGACAUCCACCGUCAGGCUAAAGGUCAGCUCCACAGCCGUAAGGACACAGCACACAACCACCCGACCUGUUCCCGACACCUCCCGGCUGCCUGGGGCCACCCCUGGGCUCACCACGGUGGAGAUAGUGACAAUGUCUCACCAAGCUCUGGGCGACGUUGCUGGCAGAGGAAAUGAGAAGAAGCCCAGUAGCGUGAGGGCUCUGUCCAUUGUCCUCCCCAUCGUGCUCCUCGUCUUCCUUUGCCUGGGGGUCUUCCUUCUAUGGAAGAACUGGCGGCUUAAGAACAUCAACAGCAUCAACUUUGACAACCCCGUCUAUCAGAAGACCACAGAGGAUGAGGUCCACAUUUGCCACAACCAGGACGGCUACAGCUACCCCUCGAGACAGAUGGUCAGUCUGGAGGAUGACGUGGCGUGAACAUCUGCCUGGAGUCCCGUCCCUGCCCAGAACCCUUCCUGAGACCUCGCCGGCCUUGUUUUAUUCAAAGACAGAGAAGACCAAAGCAUUGCCUGCCAGAGCUUUGUUUUAUAUAUUUAUUCAUCUGGGAGGCAGAACAGGCUUCGGACAGUGCCCAUGCAAUGGCUUGGGUUGGGAUUUUGGUUUCUUCCUUUCCUCGUGAAGGAUAAGAGAAACAGGCCCGGGGGGACCAGGAUGACACCUCCAUUUCUCUCCAGGAAGUUUUGAGUUUCUCUCCACCGUGACACAAUCCUCAAACAUGGAAGAUGAAAGGGGAGGGGAUGUCAGGCCCAGAGAAGCAAGUGGCUUUCAACACACAACAGCAGAUGGCACCAACGGGACCCCCUGGCCCUGCCUCAUCCACCAAUCUCUAAGCCAAACCCCUAAACUCAGGAGUCAACGUGUUUACCUCUUCUAUGCAAGCCUUGCUAGACAGCCAGGUUAGCCUUUGCCCUGUCACCCCCGAAUCAUGACCCACCCAGUGUCUUUCGAGGUGGGUUUGUACCUUCCUUAAGCCAGGAAAGGGAUUCAUGGCGUCGGAAAUGAUCUGGCUGAAUCCGUGGUGGCACCGAGACCAAACUCAUUCACCAAAUGAUGCCACUUCCCAGAGGCAGAGCCUGAGUCACUGGUCACCCUUAAUAUUUAUUAAGUGCCUGAGACACCCGGUUACCUUGGCCGUGAGGACACGUGGCCUGCACCCAGGUGUGGCUGUCAGGACACCAGCCUGGUGCCCAUCCUCCCGACCCCUACCCACUUCCAUUCCCGUGGUCUCCUUGCACUUUCUCAGUUCAGAGUUGUACACUGUGUACAUUUGGCAUUUGUGUUAUUAUUUUGCACUGUUUUCUGUCGUGUGUGUUGGGAUGGGAUCCCAGGCCAGGGAAAGCCCGUGUCAAUGAAUGCCGGGGACAGAGAGGGGCAGGUUGACCGGGACUUCAAAGCCGUGAUCGUGAAUAUCGAGAACUGCCAUUGUCGUCUUUAUGUCCGCCCACCUAGUGCUUCCACUUCUAUGCAAAUGCCUCCAAGCCAUUCACUUCCCCAAUCUUGUCGUUGAUGGGUAUGUGUUUAAAACAUGCACGGUGAGGCCGGGCGCAGUGGCUCACGCCUGUAAUCCCAGCACUUUGGGAGGCCGAGGCGGGUGGAUCAUGAGGUCAGGAGAUCGAGACCAUCCUGGCUAACACGUGAAACCCCGUCUCUACUAAAAAUACAAAAAAUUAGCCGGGCGUGGUGGCGGGCACCUGUAGUCCCAGCUACUCGGGAGGCUGAGGCAGGAGAAUGGUGUGAACCCGGGAAGCGGAGCUUGCAGUGAGCCGAGAUUGCGCCACUGCAGUCCGCAGUCUGGCCUGGGCGACAGAGCGAGACUCCGUCUCAAAAAAAAAAAACAAAAAAAAACCAUGCAUGGUGCAUCAGCAGCCCAUGGCCUCUGGCCAGGCAUGGCGAGGCUGAGGUGGGAGGAUGGUUUGAGCUCAGGCAUUUGAGGCUGUCGUGAGCUAUGAUUAUGCCACUGCUUUCCAGCCUGGGCAACAUAGUAAGACCCCAUCUCUUAAAAAAUGAAUUUGGCCAGACACAGGUGCCUCACGCCUGUAAUCCCAGCACUUUGGGAGGCUGAGCUGGAUCACUUGAGUUCAGGAGUUGGAGACCAGGCCUGAGCAACAAAGCGAGAUCCCAUCUCUACAAAAACCAAAAAGUUAAAAAUCAGCUGGGUACGGUGGCACGUGCCUGUGAUCCCAGCUACUUGGGAGGCUGAGGCAGGAGGAUCGCCUGAGCCCAGGAGGUGGAGGUUGCAGUGAGCCAUGAUCGAGCCACUGCACUCCAGCCUGGGCAACAGAUGAAGACCCUAUUUCAGAAAUACAACUAUAAAAAAAUAAAUAAAUCCUCCAGUCUGGAUCGUUUGACGGGACUUCAGGUUCUUUCUGAAAUCGCCGUGUUACUGUUGCACUGAUGUCCGGAGAGACAGUGACAGCCUCCGUCAGACUCCCGCGUGAAGAUGUCACAAGGGAUUGGCAAUUGUCCCCAGGGACAAAACACUGUGUCCCCCCCAGUGCAGGGAACCGUGAUAAGCCUUUCUGGUUUCGGAGCACGUAAAUGCGUCCCUGUACAGAUAGUGGGGAUUUUUUGUUAUGUUUGCACUUUGUAUAUUGGUUGAAACUGUUAUCACUUAUAUAUAUAUAUAUACACACAUAUAUAUAAAAUCUAUUUAUUUUUGCAAACCCUGGUUGCUGUAUUUGUUCAGUGACUAUUCUCGGGGCCCUGUGUAGGGGGUUAUUGCCUCUGAAAUGCCUCUUCUUUAUGUACAAAGAUUAUUUGCACGAACUGGACUGUGUGCAACGCUUUUUGGGAGAAUGAUGUCCCCGUUGUAUGUAUGAGUGGCUUCUGGGAGAUGGGUGUCACUUUUUAAACCACUGUAUAGAAGGUUUUUGUAGCCUGAAUGUCUUACUGUGAUCAAUUAAAUUUCUUAAAUGAACCAA",
                                "Protein_sequence": "MGPWGWKLRWTVALLLAAAGTAVGDRCERNEFQCQDGKCISYKWVCDGSAECQDGSDESQETCLSVTCKSGDFSCGGRVNRCIPQFWRCDGQVDCDNGSDEQGCPPKTCSQDEFRCHDGKCISRQFVCDSDRDCLDGSDEASCPVLTCGPASFQCNSSTCIPQLWACDNDPDCEDGSDEWPQRCRGLYVFQGDSSPCSAFEFHCLSGECIHSSWRCDGGPDCKDKSDEENCAVATCRPDEFQCSDGNCIHGSRQCDREYDCKDMSDEVGCVNVTLCEGPNKFKCHSGECITLDKVCNMARDCRDWSDEPIKECGTNECLDNNGGCSHVCNDLKIGYECLCPDGFQLVAQRRCEDIDECQDPDTCSQLCVNLEGGYKCQCEEGFQLDPHTKACKAVGSIAYLFFTNRHEVRKMTLDRSEYTSLIPNLRNVVALDTEVASNRIYWSDLSQRMICSTQLDRAHGVSSYDTVISRDIQAPDGLAVDWIHSNIYWTDSVLGTVSVADTKGVKRKTLFRENGSKPRAIVVDPVHGFMYWTDWGTPAKIKKGGLNGVDIYSLVTENIQWPNGITLDLLSGRLYWVDSKLHSISSIDVNGGNRKTILEDEKRLAHPFSLAVFEDKVFWTDIINEAIFSANRLTGSDVNLLAENLLSPEDMVLFHNLTQPRGVNWCERTTLSNGGCQYLCLPAPQINPHSPKFTCACPDGMLLARDMRSCLTEAEAAVATQETSTVRLKVSSTAVRTQHTTTRPVPDTSRLPGATPGLTTVEIVTMSHQALGDVAGRGNEKKPSSVRALSIVLPIVLLVFLCLGVFLLWKNWRLKNINSINFDNPVYQKTTEDEVHICHNQDGYSYPSRQMVSLEDDVA",
                                "Protein_ID": "NP_000518.1"
                        }
    '''

    # Email required to access genbank records.
    Entrez.email = email

    # Efetch used to query nucleotide database on genbank and return the record as text.
    with Entrez.efetch(db='nucleotide', rettype='gb', retmode='text', id=accession_ID) as handle:

        # Iterates through each object in the record.
        for seq_record in SeqIO.parse(handle, 'gb'):

            # Iterates through each item in the 'features' record object.
            for feature in seq_record.features:

                # Accesses the information stored in the 'CDS' (Coding DNA Sequence) feature, in the record.
                if feature.type == 'CDS':

                    # Stores the gene symbol, protein sequence accession number, HGNC ID and protein sequence in a
                    # dictionary called, 'CDS_dict'.
                    CDS_dict = {
                        'gene': feature.qualifiers['gene'],
                        'protein_id': feature.qualifiers['protein_id'],
                        'db_xref': feature.qualifiers['db_xref'],
                        'translation': feature.qualifiers['translation']
                    }

            # Stores the content from the CDS_dict, as well as other objects in the record, in a dictionary called,
            # 'record_dict'
            record_dict = {
                'ID': seq_record.id,
                'Gene_symbol': CDS_dict['gene'][0],
                'HGNC_ID': CDS_dict['db_xref'][2].split(':')[2],
                'DNA_sequence': str(seq_record.seq),
                'RNA_sequence': str(seq_record.seq.replace("T", "U")),
                'Protein_sequence': CDS_dict['translation'][0],
                'Protein_ID': CDS_dict['protein_id'][0]
            }

    # Commented-out code that allows the user to view the content of record_dict if the # is removed.
    #print(json.dumps(record_dict, indent=4))

    # record_dict is returned as the output.
    return record_dict


#record = objectify(entrezFetchTranscriptRecord('A.N.Other@example.com', 'NM_000527.5'))